version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - bash ./gradlew clean bootJar
      - mv build/libs/tracker-0.0.1-SNAPSHOT.jar tracker-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - tracker-0.0.1-SNAPSHOT.jar